# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa5e8927f918ed40f2351f03a38b05b78e2d33aca251dc563007305285b37bc4b4426c01aa7199ed5d9ff5177bb7860682fe835e53eece3ad1bab836587fefc3

test:
  secret_key_base: 80df23dc536ece26851f251ba6bda78ca49e0146e8ce50039b5a4a97b70d4d2780ce9f49c40b1f018639487f30ad3512e974138498c44bc6a549440b5f9d92f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
